### ISSUE TITLE
Erreur suite git pull

### ISSUE THREAD

**Issue by Sigri44** [LaBaleineFr/LaBaleineDeWallStreet#10]
Salut à tous,

J'ai vu qu'il y avait pas mal de nouveauté, j'ai donc mis à jour mon bot, et depuis : 

```
root@docker ~/scripts # ./discord_labaleine.sh
aborting bot
Traceback (most recent call last):
  File "/root/scripts/LaBaleineDeWallStreet/main.py", line 25, in main
    mainbot = bot.Bot(conf.settings, loop=loop)
  File "/root/scripts/LaBaleineDeWallStreet/baleine/bot.py", line 29, in __init__
    self.plugins = self.load_plugins(settings)
  File "/root/scripts/LaBaleineDeWallStreet/baleine/bot.py", line 43, in load_plugins
    result.append(klass(config))
  File "/root/scripts/LaBaleineDeWallStreet/baleine/plugins/naming.py", line 50, in __init__
    with open(badwords, 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'data/badwords'
```

J'ai bien rajouté la variable SETTINGS.

J'ai aussi essayé de passer par Docker mais je crois que c'est pire..
Le bot se lance bien, aucune erreur, mais le bot réagit pas dans le discord (je passe par portainer)

**Comment by daodevinc** [comment]
Pour la partie Docker, dans les logs : 
```
ERROR [bot] ValueError in on_ready event: Role dev not found
```
Et après avoir créé le rôle dev et l'avoir assigné au bot :
```
ERROR [bot] ValueError in on_ready event: Channel bot not found
```

Pourtant le bot avait déjà un rôle généré automatiquement par le script nommé `LaBaleineDeWallStreet`.

**Comment by Batalex** [comment]
Dans le premier log d'erreur, c'est indiqué qu'il te manque le fichier badwords, as-tu essayé de l'ajouter ? Par ailleurs, comment configure tu ton bot ? Si tu utilises des réglages plutôt spécifiques au discord de la baleine c'est normal que ça ne marche pas pareil dans ton cas particulier à toi

**Comment by daodevinc** [comment]
Non je ne l'ai pas ajouté ^^ C'est plus un bot de conversion altcoin, c'est carrément un modo maintenant ?

Je configure le TOKEN du bot et go, ça marchait comme ça avec la version du mois dernier du moins.

**Comment by Batalex** [comment]
Yup, il devient un modo-bot. En attendant que nous fassions un README un peu plus clair, ou même carrément que nous mettions à disposition une configuration minimale pour ceux comme toi effectivement qui ne veulent que mettre le token et que ça marche pour la conversion, tu peux rester sur les versions antérieures

**Comment by daodevinc** [comment]
Cool merci ! ;) On peut clone un ancien commit ? :) 
Sinon je dois avoir ça en stock.
Oui car j'ai déjà un bot qui fait le modo et je préfère pas mélanger (vaut mieux jamais centraliser ;))
Il y'a pas eu de mise à jour de certains tokens depuis ? Style ETN, etc ?

**Comment by spectras** [comment]
Yep tu peux trouver le bot d'avant la refonte sur ce commit là :
https://github.com/LaBaleineFr/LaBaleineDeWallStreet/tree/aafd2daeab3616bc33b430802c4a0ae210fd0d8b

Effectivement le bot est en train de changer de focus pour s'occuper de l'administration.
Toutes les fonctions sont activables ou désactivables une à une. Il suffit de les retirer dans le fichier de configuration.

**Comment by daodevinc** [comment]
Cool merci effectivement ça passe !
